blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/dpdanpittman/HamHub-app/discussions
    about: Ask questions and discuss ideas with the community
